---
title: "DataAnalysis"
output: html_document
date: "2023-12-17"
---

```{r}
library(readr)
library(Stat2Data)
library(metRology) # for curve plotting
library(tidyr) # easy functions and syntax for creating tidy data
library(car)    # useful functions for regressions
library(corrplot) # for nice plots of correlation matrices
library(leaps) # package for model selection
library(polynom) # building polynomials from polynomial regression
library(titanic)
library(bestglm)
library(gmodels) # Compute and test arbitrary contrasts
library(dplyr)
library(knitr)
library(MASS)
library(ggplot2)
```

```{r}
#READING IN DATA, REFORMATTING DATA TO MAKE IT USEFUL
data <- read.csv("Data1.csv")
data2 <- read.csv("Data2.csv")
data3 <- read.csv("Data3.csv")
data4 <- read.csv("Data4.csv")
data5 <- read.csv("Data5.csv") 
databind <- rbind(data, data2, data3, data4, data5)
data_adj <- databind[, c(1, 5:ncol(databind))]
WNB_data <- subset(data, wides == 1 | noballs == 1)
data_adj$wides[is.na(data_adj$wides)] <- 0
data_adj$wides[data_adj$wides > 0] <- 1
data_adj$noballs[is.na(data_adj$noballs)] <- 0
data_adj$noballs[data_adj$noballs > 0] <- 1
data_adj$error[data_adj$noballs == 1 | data_adj$wides == 1] <- 1
data_adj$error[is.na(data_adj$error)] <- 0
halfway_row <- nrow(data_adj) %/% 2
dataset1 <- data_adj[1:10000, ]
dataset2 <- data_adj[(halfway_row + 1):nrow(data_adj), ]

#CREATING FATIGUE VARIABLE
data_adj <- data_adj %>%
  arrange(match_id, ball) %>%
  group_by(match_id, striker) %>%
  mutate(striker_fatigue = cumsum(lag(ball, default = first(ball), order_by = match_id) > ball - 1)) %>%
  ungroup() %>%
  group_by(match_id, non_striker) %>%
  mutate(non_striker_fatigue = cumsum(lag(ball, default = first(ball), order_by = match_id) > ball - 1)) %>%
  ungroup() %>%
  group_by(match_id, bowler) %>%
  mutate(bowler_fatigue = cumsum(lag(ball, default = first(ball), order_by = match_id) > ball - 1)) %>%
  ungroup()

```

```{r}
#VARIABLES I CREATED TO INITIALLY LOOK AT DATA
striker_counts <- data_adj %>% count(striker)
bowler_counts <- data_adj %>% count(bowler)

threshold_striker <- 1000  # Set your desired threshold
threshold_bowler <- 1000   # Set your desired threshold

data_adj <- data_adj %>%
  left_join(striker_counts %>% rename(count_striker = n), by = "striker") %>%
  mutate(frequency_striker = ifelse(count_striker >= threshold_striker, "Frequent", "Infrequent")) %>%   left_join(bowler_counts %>% rename(count_bowler = n), by = "bowler") %>%
  mutate(frequency_bowler = ifelse(count_bowler >= threshold_bowler, "Frequent", "Infrequent")) # Remove the count column

bowler_runs <- data_adj %>%
  group_by(bowler) %>%
  summarise(total_runs_against = sum(runs_off_bat))

# Calculate total runs scored by each striker
striker_runs <- data_adj %>%
  group_by(striker) %>%
  summarise(total_runs_by = sum(runs_off_bat))

ggplot(striker_runs, aes(x = total_runs_by)) +
  geom_histogram(binwidth = 20, fill = "skyblue", color = "black") +
  labs(title = "Distribution of Runs Scored by Strikers", x = "Total Runs", y = "Frequency")

# Histogram for runs scored against bowlers
ggplot(bowler_runs, aes(x = total_runs_against)) +
  geom_histogram(binwidth = 20, fill = "lightgreen", color = "black") +
  labs(title = "Distribution of Runs Scored Against Bowlers", x = "Total Runs", y = "Frequency")

data_adj <- data_adj %>%
  left_join(bowler_runs, by = "bowler") %>%
  left_join(striker_runs, by = "striker")

#CALCULATING RUNS PER OVER FOR BOWLERS AND STRIKERSz
data_adj$runs_per_over_bowler <- data_adj$total_runs_against / (data_adj$count_bowler / 6)
data_adj$bowler_performance <- cut(data_adj$runs_per_over_bowler,
                                        breaks = c(-Inf, 2, 3, 4, Inf),
                                        labels = c("Elite", "Good", "Average", "Bad"),
                                        right = FALSE)

data_adj$runs_per_over_striker <- data_adj$total_runs_by / (data_adj$count_striker / 6)
data_adj$striker_performance <- cut(data_adj$runs_per_over_striker,
                                        breaks = c(-Inf, 2, 3, 5, Inf),
                                        labels = c("Bad", "Average", "Good", "Elite"),
                                        right = FALSE)
data_adj_filtered <- data_adj %>%
  group_by(bowler) %>%
  filter(count_bowler >= 200) %>%
  ungroup() %>%
  group_by(striker) %>%
  filter(count_striker >= 200) %>%
  ungroup()

data_adj_filtered$striker_performance <- relevel(data_adj_filtered$striker_performance, ref = "Average")
data_adj_filtered$bowler_performance <- relevel(data_adj_filtered$bowler_performance, ref = "Average")


```

```{r}
initial_model_wides1 <- glm(wides ~ factor(frequency_striker), data = top_bowler_data, family = binomial(link = "logit"))
summary(initial_model_wides1)

```
```{r}
initial_model_wides2 <- glm(wides ~ factor(frequency_bowler), data = top_striker_data, family = binomial(link = "logit"))
summary(initial_model_wides2)
```
```{r}
initial_model_wides3 <- glm(wides ~ factor(frequency_bowler) + factor(frequency_striker), data = data_adj, family = binomial(link = "logit"))
summary(initial_model_wides3)
```

```{r}
wides_model_with_performance <- glm(wides ~ factor(bowler_performance) + factor(striker_performance), data = data_adj_filtered, family = binomial(link = "logit"))
summary(wides_model_with_performance)

coef_df <- data.frame(
  Predictor = c("Bowler_Performance_Elite", "Bowler_Performance_Good", "Bowler_Performance_Bad",
                "Striker_Performance_Bad", "Striker_Performance_Good", "Striker_Performance_Elite"),
  LogOdds = c(0.05, -0.82, 0.85, -0.22, 0.60, 1.18)
)

# Convert log odds to odds ratios
coef_df$OddsRatio <- exp(coef_df$LogOdds)

# Display the dataframe with odds ratios
print(coef_df)

ggplot(coef_df, aes(x = Predictor, y = OddsRatio)) +
  geom_bar(stat = "identity", fill = "skyblue", width = 0.5) +
  labs(title = "Odds Ratios of Wide Occurrence",
       x = "Predictor",
       y = "Odds Ratio") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot(wides_model_with_performance)
```
```{r}
wides_bowlermodel_with_performance <- glm(wides ~ factor(bowler_performance), data = data_adj_filtered, family = binomial(link = "logit"))
summary(wides_bowlermodel_with_performance)
```
```{r}
wides_strikermodel_with_performance <- glm(wides ~  factor(striker_performance), data = data_adj_filtered, family = binomial(link = "logit"))
summary(wides_strikermodel_with_performance)
```


```{r}
noballs_model_with_performance <- glm(noballs ~ factor(bowler_performance) + factor(striker_performance), data = data_adj_filtered, family = binomial(link = "logit"))
summary(noballs_model_with_performance)
```

```{r}
full_model_with_performance <- glm(error ~ factor(bowler_performance) + factor(striker_performance), data = data_adj_filtered, family = binomial(link = "logit"))
summary(full_model_with_performance)
```
```{r}
#STRIKER PERFORMANCE FINAL MODEL
errorstriker_model_with_performance <- glm(error ~ factor(striker_performance), data = data_adj_filtered, family = binomial(link = "logit"))
summarystriker <- summary(errorstriker_model_with_performance)

# Extract coefficients
coef_table1 <- summarystriker$coefficients

# Extract coefficients for the factors
coef_factors1 <- coef_table1[-1, ]

# Calculate odds ratios
odds_ratios1 <- (exp(coef_factors1[, 1]) / (1 + exp(coef_factors1[, 1]))) *100

# Create a data frame for plotting
odds_df <- data.frame(
  Performance = rownames(coef_factors1),
  OddsRatio = odds_ratios1
)

odds_bad <- (exp(-0.09094) / (1 + exp(-0.09094))) * 100
odds_good <- (exp(0.40047) / (1 + exp(0.40047))) * 100
odds_elite <- (exp(0.95059) / (1 + exp(0.95059))) * 100


odds_df$OddsRatio[odds_df$Performance == "factor(striker_performance)Bad"] <- -1 * odds_df$OddsRatio[odds_df$Performance == "factor(striker_performance)Bad"]


ggplot(odds_df, aes(x = reorder(Performance, OddsRatio), y = OddsRatio)) +
  geom_bar(stat = "identity", fill = "skyblue", width = 0.5) +
  geom_text(aes(label = paste0(sprintf("%.2f", OddsRatio), "%"), y = OddsRatio), vjust = -0.5, size = 3) + 
  labs(title = "Effect of Striker Performance on Error Likelihood (%) Compared to Average Striker",
       x = "Striker Performance Level",
       y = "Error Likelihood") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) + 
   scale_x_discrete(labels = c("factor(striker_performance)Good" = "Good Striker", "factor(striker_performance)Elite" = "Elite Striker", "factor(striker_performance)Bad" = "Poor Striker"))
```
```{r}
#BOWLER PERFORMANCE FINAL MODEL
errorbowler_model_with_performance <- glm(error ~ factor(bowler_performance), data = data_adj_filtered, family = binomial(link = "logit"))
summary(errorbowler_model_with_performance)
summarybowler <- summary(errorbowler_model_with_performance)

# Extract coefficients
coef_table2 <- summarybowler$coefficients

# Extract coefficients for the factors
coef_factors2 <- coef_table2[-1, ]

# Calculate odds ratios
odds_ratios2 <- (exp(coef_factors2[, 1]) / (1 + exp(coef_factors2[, 1]))) *100

# Create a data frame for plotting
odds_df2 <- data.frame(
  Performance = rownames(coef_factors2),
  OddsRatio = odds_ratios2
)


odds_df2$OddsRatio[odds_df2$Performance == "factor(bowler_performance)Good"] <- -1 * odds_df2$OddsRatio[odds_df2$Performance == "factor(bowler_performance)Good"]
odds_df2$OddsRatio[odds_df2$Performance == "factor(bowler_performance)Elite"] <- -1 * odds_df2$OddsRatio[odds_df2$Performance == "factor(bowler_performance)Elite"]

odds_df2$Performance <- factor(odds_df2$Performance, levels = c("factor(bowler_performance)Bad", "factor(bowler_performance)Good", "factor(bowler_performance)Elite"))


ggplot(odds_df2, aes(x = Performance, y = OddsRatio)) +
  geom_bar(stat = "identity", fill = "skyblue", width = 0.5) +
  geom_text(aes(label = paste0(sprintf("%.2f", OddsRatio), "%"), y = OddsRatio), vjust = -0.5, size = 3) + 
  labs(title = "Effect of Bowler Performance on Error Likelihood (%) Compared to Average Bowler",
       x = "Bowler Performance Level",
       y = "Error Likelihood") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) + 
   scale_x_discrete(labels = c("factor(bowler_performance)Good" = "Good Bowler", "factor(bowler_performance)Elite" = "Elite Bowler", "factor(bowler_performance)Bad" = "Poor Bowler"))
```


```{r}
#FATIGUE FINAL MODEL
lowfatigue_data <- subset(data_adj_filtered, striker_fatigue < 200)
lowfatigue_model <- glm(error ~ striker_fatigue, data = lowfatigue_data, family = binomial(link = "logit"))
fatigue_model <- glm(error ~ striker_fatigue + bowler_fatigue, data = data_adj_filtered, family = binomial(link = "logit"))
summary(fatigue_model)
summaryfatigue <- summary(fatigue_model)

coef_table3 <- summaryfatigue$coefficients

# Extract coefficients for the factors (excluding intercept)
coef_factors3 <- coef_table3[-1, ]

# Calculate odds ratios
odds_ratios3 <- (exp(coef_factors3[, 1]))

# Create a data frame for plotting
odds_df3 <- data.frame(
  fatiguelevel = rownames(coef_factors3),
  OddsRatio = odds_ratios3
)

ggplot(odds_df3, aes(x = fatiguelevel, y = OddsRatio)) +
  geom_bar(stat = "identity", fill = "skyblue", width = 0.5) +
  geom_text(aes(label = paste0(sprintf("%.3f", OddsRatio)), y = OddsRatio), vjust = -0.5, size = 3) + 
  labs(title = "Impact of Fatigue Level on Error Likelihood",
       x = "Position Played",
       y = "Odds Ratio") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) + 
   scale_x_discrete(labels = c("bowler_fatigue" = "Bowler Fatigue", "striker_fatigue" = "Striker Fatigue"))

ggplot(data_adj_filtered, aes(x = bowler_fatigue, y = error)) +
  geom_point() +  # Scatterplot
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = FALSE) +  # Logistic regression line
  labs(title = "Effect of Bowler Fatigue on Errors",
       x = "Fatigue Measure",
       y = "Probability of Error") +
  theme_minimal()


```

